### ISSUE TITLE
ModuleNotFoundError: No module named 'idlelib.MultiStatusBar'

### ISSUE THREAD

**Issue by freetz13** [PyEditor/PyEditor#1]
Installed with pip to python3 on Windows 10.
```
C:\Users\user>pyeditor
Traceback (most recent call last):
  File "C:\Python36-32\lib\site-packages\pyeditor\__main__.py", line 18, in <module>
    from pyeditor.editor_window import EditorWindow
  File "C:\Python36-32\lib\site-packages\pyeditor\editor_window.py", line 10, in <module>
    from pyeditor.tk_helpers.mymultistatusbar import MyMultiStatusBar
  File "C:\Python36-32\lib\site-packages\pyeditor\tk_helpers\mymultistatusbar.py", line 2, in <module>
    from idlelib.MultiStatusBar import MultiStatusBar
ModuleNotFoundError: No module named 'idlelib.MultiStatusBar'
```

**Comment by jedie** [comment]
Maybe you didn't install the idelib at all. Or is it the wrong version?

**Comment by freetz13** [comment]
```
C:\Users\user>pip install idlelib
Collecting idlelib
  Using cached idlelib-1505331088.9901652.tar.gz
Installing collected packages: idlelib
  Running setup.py install for idlelib ... error
    Complete output from command c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-build-x1v2kvyn\\idlelib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-xc0h3gsc-record\install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-x1v2kvyn\idlelib\setup.py", line 27, in <module>
        "This is a bogus package that should not be installed\n\n"
    Exception: This is a bogus package that should not be installed

    Please read https://www.pytosquatting.org

    ----------------------------------------
Command "c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-build-x1v2kvyn\\idlelib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-xc0h3gsc-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-build-x1v2kvyn\idlelib\
```

**Comment by jedie** [comment]
Sorry, now I see that you're working under windows. In this case, the idlelib is usually always installed.

I added the file https://github.com/PyEditor/PyEditor/blob/master/boot_PyEditor.cmd and try this here on Windows 10 with Python v3.5.1 and it works fine:

![screenshot](https://user-images.githubusercontent.com/71315/30531864-2a61abb0-9c51-11e7-91f9-facba1bc7848.JPG)

Can you post the output from:

```
import idlelib
print(idlelib.__file__)
```
Here it's: `C:\Program Files (x86)\Python35-32\lib\idlelib\__init__.py`

What Python install package have you used?!?

**Comment by freetz13** [comment]
Sorry, I forgot to tell you my version is **3.6.1**. I've run `boot_PyEditor.cmd` but no luck. I realized that there is some changes in `idlelib` - some files was renamed somewhere between 3.5.1 and 3.6.1. Look what i did:

- In `pyeditor/editor_window.py`:
    - `idlelib.ColorDelegator` -> `idlelib.colorizer`
    - `idlelib.MultiStatusBar` -> `idlelib.statusbar`
    - `idlelib.Percolator` -> `idlelib.percolator`
- In `pyeditor/tk_helpers/mymultistatusbar.py`:
    - `idlelib.MultiStatusBar` -> `idlelib.statusbar`

That worked for me.

**Comment by jedie** [comment]
Good point. Can you create a pull request with import updates that will work with 3.5 and 3.6 ?

**Comment by freetz13** [comment]
Done. Sorry, I'm not as good in Git like in Python

**Comment by jedie** [comment]
Thanks. I release v0.2.1 with you changes.
